name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: registry.gitlab.com/pages/hugo/hugo_extended:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Hugo
        run: |
          apk add --update --no-cache git go nodejs npm
          hugo mod tidy
          hugo mod npm pack
          npm install
      - name: Hugo Build
        run: $HOME/hugo --minify -v
      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        run: $HOME/hugo -v deploy --maxDeletes -1 --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
